dubbo:
  application:
    name: demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848


server:
  port: 8809

spring:
  application:
    name: demo-consumer
